// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc3699.FRC3699;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainLeftMotor;
    public static SpeedController driveTrainRightMotor;
    public static RobotDrive driveTrainRobotDrive;
    public static SpeedController intakeSystemMotor;
    public static SpeedController elevatorMotor;
    public static SpeedController shooterMotor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainLeftMotor = new Jaguar(1, 1);
	LiveWindow.addActuator("Drive Train", "Left Motor", (Jaguar) driveTrainLeftMotor);
        
        driveTrainRightMotor = new Jaguar(1, 2);
	LiveWindow.addActuator("Drive Train", "Right Motor", (Jaguar) driveTrainRightMotor);
        
        driveTrainRobotDrive = new RobotDrive(driveTrainLeftMotor, driveTrainRightMotor);
	
        driveTrainRobotDrive.setSafetyEnabled(true);
        driveTrainRobotDrive.setExpiration(0.1);
        driveTrainRobotDrive.setSensitivity(0.5);
        driveTrainRobotDrive.setMaxOutput(1.0);
        
        intakeSystemMotor = new Jaguar(1, 3);
	LiveWindow.addActuator("Intake System", "Motor", (Jaguar) intakeSystemMotor);
        
        elevatorMotor = new Jaguar(1, 5);
	LiveWindow.addActuator("Elevator", "Motor", (Jaguar) elevatorMotor);
        
        shooterMotor = new Jaguar(1, 4);
	LiveWindow.addActuator("Shooter", "Motor", (Jaguar) shooterMotor);
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
